### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by enyo** [supercharge/mongodb-github-action#14]
I'm running my tests in a docker container. So connecting to the mongodb container doesn't work. Do you know of a way to make these two containers communicate with each other? Do I need docker compose for that?

**Comment by marcuspoehls** [comment]
@enyo Hey Matias, are you running your tests locally on your machine? What operating system are you using? Windows?

**Comment by enyo** [comment]
Hey, I tried running them on GitHub actions first, and then started working on running them locally, but realised that the problem was, that I'm starting two docker containers that need to interact with one another.

**Comment by enyo** [comment]
To explain it a bit better: I want to run my tests in the `google/dart` docker container. So I have:

```yaml
container:
  image: google/dart:latest
```

in my workflow yaml file.

This causes my steps to run inside a docker container themselves instead of the virtual machine directly. Since my steps are now inside a docker container themselves, they can't connect to `localhost:27017` anymore.

**Comment by marcuspoehls** [comment]
@enyo Ah, now I understand your setup. What I’m thinking of is [GitHub Actions Services](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idservices).

Here’s a short description from the docs:

> Used to host service containers for a job in a workflow. Service containers are useful for creating databases or cache services like Redis. The runner automatically creates a Docker network and manages the life cycle of the service containers.

I guess the Docker network part is important to have all services and apps connect to each other.

Did you already try services?

**Comment by enyo** [comment]
Hi! Thanks, that was exactly what I was looking for.

**Comment by marcuspoehls** [comment]
@enyo Sweet! Good you found it 👍
