### ISSUE TITLE
Documentation: unclear on what address the mongodb is started

### ISSUE THREAD

**Issue by glensc** [supercharge/mongodb-github-action#16]
What is the address of MongoDB? documentation only says port...

> This GitHub Action starts a MongoDB server or MongoDB replica set on the default port 27017.

- https://github.com/marketplace/actions/mongodb-in-github-actions

example failed run:
- https://github.com/perftools/xhgui/runs/1326259015

**Comment by marcuspoehls** [comment]
@glensc Hey Elan, the default MongoDB service is available on `localhost:27017`

**Comment by glensc** [comment]
Why is that job failing then? how to test the service booted up?

**Comment by glensc** [comment]
Nevermind then, using "services" which just works:
- https://github.com/actions/example-services/pull/21

**Comment by marcuspoehls** [comment]
@glensc Sweet! Thank you for sharing your solution!
