### ISSUE TITLE
How should I call the URL of my connection to mongodb in my code?

### ISSUE THREAD

**Issue by cristian-programmer** [supercharge/mongodb-github-action#18]
Hello, first thank you very much for this contribution
I have a little doubt, I use mongo in my integration tests, but I don't know how I should declare my connection string in my source code so that I can access the database.

**Comment by marcuspoehls** [comment]
@cristian-programmer Hey, the MongoDB database provisioned in GitHub Actions is available on `localhost:27017`. Did you try this URL as your connection string?

**Comment by cristian-programmer** [comment]
Not. I will try, thank you very much, I have something different. :)

**Comment by marcuspoehls** [comment]
@cristian-programmer Hey, did you solve your problem?

**Comment by cristian-programmer** [comment]
@marcuspoehls   Hi, thanks, this working now.

**Comment by marcuspoehls** [comment]
@cristian-programmer Awesome!
