### ISSUE TITLE
[Feature Request] Custom Port

### ISSUE THREAD

**Issue by einfallstoll** [supercharge/mongodb-github-action#20]

**Comment by marcuspoehls** [comment]
@einfallstoll Hey Fabio, would you like to submit a pull request adding the custom port feature?

**Comment by einfallstoll** [comment]
I figured out I don't need it. But I built it anyway. This thing already saved me some time, so it's worth to spend some time on this 😁

**Comment by marcuspoehls** [comment]
@einfallstoll Haha 😄  Thank you for spending the time creating the pull request!
