### ISSUE TITLE
MongoDB latest (4.4) is pulled when requesting 4.0

### ISSUE THREAD

**Issue by davidlatwe** [supercharge/mongodb-github-action#22]
If we request version `4.0` as float, github action (or it was YAML ?) interpret it as integer `4` and the latest version (currently `4.4+`) is pulled.
See [log](https://github.com/supercharge/mongodb-github-action/runs/2553447529?check_suite_focus=true#step:3:111) of this project for example.

To overcome this, we should request by string `"4.0"`.

**Comment by marcuspoehls** [comment]
@davidlatwe Hey David, thank you for pointing this out! I didn’t notice this version glitch. Thank you!

**Comment by marcuspoehls** [comment]
@davidlatwe Fixed in version `1.4.1`. Published to the GitHub marketplace
