### ISSUE TITLE
Looking for Release notes

### ISSUE THREAD

**Issue by tebeco** [supercharge/mongodb-github-action#27]
hello, I might be using github the wrong way, but I'm trying to find what was released
I understand the repo is small for now

Idea:
avoid to open 1.6.x release / check commit / clone / do a diff on a git tree of all merge PR

Here are the various way I tried:

Release view:
![image](https://user-images.githubusercontent.com/2266487/146523565-b810d896-17a0-4c21-8fe0-64810c645f7a.png)

The 1.7.0 PR is just a bump PR:
<img width="858" alt="image" src="https://user-images.githubusercontent.com/2266487/146523626-681325c2-ee74-458f-831a-c249341e7166.png">

I went to check milestone for Issue / PR associated:
![image](https://user-images.githubusercontent.com/2266487/146523680-ed9b3338-0423-4c55-b3d7-4ceab5b83262.png)

same for label:
![image](https://user-images.githubusercontent.com/2266487/146523722-c47d2b7d-3044-4a93-93a1-0213a94876ab.png)

PRs without filter:
It's not in the title either
![image](https://user-images.githubusercontent.com/2266487/146523798-a6a2cb61-ba31-4864-aba3-d2ffa6fce949.png)

**Comment by marcuspoehls** [comment]
@tebeco Hey, this repository contains a [CHANGELOG.md](https://github.com/supercharge/mongodb-github-action/blob/main/CHANGELOG.md) file. This changelog includes the release notes, outlining changes between releases.

**Comment by tebeco** [comment]
good point, i forgot that was also a place to look at

i wish github attempted to integrate that

**Comment by marcuspoehls** [comment]
yeah, an integration from GitHub or a reference for an existing changelog would be nice 👍
