### ISSUE TITLE
Would you be interested in a Windows version?

### ISSUE THREAD

**Issue by danielmarbach** [supercharge/mongodb-github-action#33]
Currently, GitHub actions do not allow running Linux containers on Windows. We have a bunch of jobs that need to be executed on Windows. Currently, we maintain a custom composite action that either uses this action here for Linux or sets up a custom service on the GitHub action runner on Windows.

The relevant code for Windows is here

https://github.com/Particular/setup-mongodb-action/blob/main/action.yml#L22-L46

Would you be interested and willing to take a contribution that would bring in parts of that solution we have over there into this action? I'd be happy to contribute in case you agree.

**Comment by danielmarbach** [comment]
One of the obvious drawbacks would be that the approach is bound to what is on the runner image which means some of the options of this action would not be applicable for the windows part

**Comment by marcuspoehls** [comment]
@danielmarbach Hey Daniel, thank you for asking about Windows support and offering help to implement that in this GitHub Action. At this point, I don’t want to maintain support for this Docker action and a separate Windows action. It takes effort to keep feature parity between both. My hope is that GitHub will support Docker-based GitHub Actions on Windows too.
