### ISSUE TITLE
`mongo` and `mongosh` disappeared?

### ISSUE THREAD

**Issue by scspijker** [supercharge/mongodb-github-action#39]
Since today our builds fail because they can't find the `mongo` or `mongosh` clients. This is for both version 1.7.0 and 1.8.0 of this step.

Did this step install client software before and has something changes / broken, or did we accidentally get mongo client software from Github Actions itself?

**Comment by marcuspoehls** [comment]
@scspijker Hey Stijn, you should have either the `mongodb` command when using the MongoDB 4.x release line or `mongosh` in MongoDB 5.x and 6.x. Can you please check your GitHub Actions logs for this package and have a look which version has been used to start the MongoDB container?

**Comment by timmyg** [comment]
@scspijker @marcuspoehls seeing similar issue - we relied on this giving us `mongo` and `mongoimport` and now getting:

```mongo: not found```
and 
```mongoimport: not found```

Using mongo:5.0

**Comment by marcuspoehls** [comment]
@timmyg Hey Tim, thanks for confirming the issue. 

@scspijker @timmyg Tim, Stijn, can you please share a link to a failed GitHub Actions job? I need more details on the error and some context in which it fails.

**Comment by ringsaturn** [comment]
@marcuspoehls Hi, I made an example repo https://github.com/ringsaturn/mongodb-action-debug for this issues, and a sample CI:

- https://github.com/ringsaturn/mongodb-action-debug/actions/runs/3552964947

**Comment by marcuspoehls** [comment]
@ringsaturn Thank you for the repo! That helps.

You're using Ubuntu 22.04 on that runner. The new 22.04 runners don't have MongoDB installed anymore. [MongoDB was available on 20.04, but removed on 22.04](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#preinstalled-software).

That's the reason you can't use the `mongo`, `mongosh`, and `mongoimport` commands directly. They would be available from within the MongoDB docker container. But not directly on the 22.04 host

**Comment by ringsaturn** [comment]
@marcuspoehls  Thanks, it’s problem of Ubuntu 22.04 runner not this action.

---

For anyone interested in this problem, please track these issues:

- https://github.com/actions/runner-images/issues/5490
- https://github.com/actions/runner-images/issues/6626
- https://www.mongodb.com/community/forums/t/installing-mongodb-over-ubuntu-22-04/159931

**Comment by marcuspoehls** [comment]
@ringsaturn Thanks for sharing the links!

**Comment by AdamGerthel** [comment]
Any ideas on how to work around this? I tried installing mongo:

```yml
      - name: Install mongosh
        run: |
          sudo apt-get update
          sudo apt-get install gnupg
          wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-mongosh
```
But that didn't help. Still getting `mongo: command not found`

**Comment by marcuspoehls** [comment]
@AdamGerthel Hey Adam, GitHub Action runners using `Ubuntu-latest` doesn’t have MongoDB installed on the host system. That means you can’t use the `mongo` command. You’re installing the MongoDB Shell `mongosh` and not MongoDB directly on the host. If I understand it correctly, you must install MongoDB itself to have the `mongo` command available.

**Comment by AdamGerthel** [comment]
@marcuspoehls 

> Ubuntu-latest doesn’t have MongoDB installed on the host system. That means you can’t use the mongo command.

Yeah I know - that's what I was trying to fix by adding the "Install mongosh" step. 

> You’re installing the MongoDB Shell mongosh and not MongoDB directly on the host.

Ok, I just followed the [official install instructions](https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-ubuntu/#install-mongodb-community-edition) and thought that would work. What would be the way to install mongodb and not mongosh then?

**Comment by marcuspoehls** [comment]
@AdamGerthel 

Your MongoDB installation is missing step 4:

```bash
sudo apt-get install -y mongodb-org
```

**Comment by AdamGerthel** [comment]
Ok, thanks! Still getting the same error nonetheless:

> Run mongo --eval "db.getSiblingDB('test')"
/home/runner/work/_temp/59[6](https://github.com/AdamGerthel/cyoa-editor/actions/runs/4351976240/jobs/7604200227#step:9:7)db[7](https://github.com/AdamGerthel/cyoa-editor/actions/runs/4351976240/jobs/7604200227#step:9:8)3b-b917-44a6-b5e8-49f67dea387e.sh: line 1: mongo: command not found
Error: Process completed with exit code 127.

It looks like the install went well, so I'm not sure what the problem is. I've tried using [Act](https://github.com/nektos/act) to be able to test it locally, but for some reason, I haven't been able to get it working (which seems to be because my repo is private).

Any ideas on why `mongo` still isn't found?

**Comment by marcuspoehls** [comment]
@AdamGerthel yep, the `mongo` command is no longer part of the MongoDB 6.0 installation. Sorry, I missed that detail. MongoDB 6.0 uses `mongosh`

**Comment by AdamGerthel** [comment]
Works - thanks!

**Comment by marcuspoehls** [comment]
Sweet!
