### ISSUE TITLE
How can I Restore Dump from external location

### ISSUE THREAD

**Issue by engahmed1190** [supercharge/mongodb-github-action#40]
I will like to start the MongoDB container with a non-empty DB.

**Comment by marcuspoehls** [comment]
@engahmed1190 Hey Ahmed, please have a look at this issue: https://github.com/supercharge/mongodb-github-action/issues/39#issuecomment-1328006692

You can get an idea of restoring a MongoDB database dump from within the linked repository. This repository is an example of using a GitHub Actions runner with Ubuntu 22.04 which doesn’t have `mongod` command line tools installed. You may need an Ubuntu 20.04 runner with a `mongodb` cli command.

**Comment by engahmed1190** [comment]
Thanks @marcuspoehls .  I am currently using Ubuntu 20.4. Here is workaround 

https://github.com/actions/runner-images/issues/6626#issuecomment-1327744126

**Comment by marcuspoehls** [comment]
Great, thanks for sharing 👍
