### ISSUE TITLE
Reaching Docker Hub limit

### ISSUE THREAD

**Issue by Fabazad** [supercharge/mongodb-github-action#42]
After using several times a day this action, I get blocked with this message :
![image](https://user-images.githubusercontent.com/22477033/210828737-bd362390-e706-49af-ad47-5720f10420fe.png)
Is it possible either to give the possibility
- To cache the docker images
- To login to Docker Hub

**Comment by Fabazad** [comment]
We think that's because we use buildjet instead of github in our runs-on config

**Comment by marcuspoehls** [comment]
@Fabazad Hey, looks like rate limiting comes from using Buildjet. I assume you read the [FAQ for rate limiting on Buildjet](https://buildjet.com/for-github-actions/docs/faq#docker-rate-limiting) already.

Did you also try to login against Docker Hub increasing your rate limit? You may use the [Docker Login GitHub Action](https://github.com/docker/login-action#dockerhub).

**Comment by mrollinsiv** [comment]
We're having this same issue using buildjet. I added a docker login as the first step in my workflow but the build always runs before any of the steps so we constantly hit the rate limit.

**Comment by marcuspoehls** [comment]
@mrollinsiv I’m not using Buildjet and don’t know their service. Can’t help here, sorry

**Comment by mrollinsiv** [comment]
@marcuspoehls my guess is this is actually just a GHA issue. I ran a build on both `ubuntu-latest` and `buildjet`. Both yeilded the same order of operations.

Here's an image of the order in which GHA runs:

<img width="388" alt="Screenshot 2023-08-09 at 5 12 20 PM" src="https://github.com/supercharge/mongodb-github-action/assets/6053943/4261ea8f-0945-48a0-a88d-2cfafd7072cc">

The builds are run before any of the steps run. Which means that even if I use the docker login step it's run too late.

I'll move to GHA as the source of the issue.

**Comment by BioCarmen** [comment]
@mrollinsiv are you able to resolve this?
