### ISSUE TITLE
Mongodb tools

### ISSUE THREAD

**Issue by euberdeveloper** [supercharge/mongodb-github-action#46]
it would be great to have an option in which it can be specified to install also the mongodb tools (e.g. mongorestore).

Initially by using your action I had them for free, but now without changing anything they are no more installed

**Comment by euberdeveloper** [comment]
By updating to 1.8.0 it is working

**Comment by marcuspoehls** [comment]
@euberdeveloper Hey Eugenio, looks like your GitHub Actions Runner is using a new version. Please have a look at this related issue: https://github.com/supercharge/mongodb-github-action/issues/39
