### ISSUE TITLE
single-instance can complete before ready to accept connections

### ISSUE THREAD

**Issue by brettmc** [supercharge/mongodb-github-action#49]
I'm hitting a race condition when using this action (v1.9.0) in single-instance mode. It can take a few seconds before mongo is ready to accept connections, so if my dependant job starts too quickly, mongo in unavailable.

My workarounds so far:
1. sleep to give mongo time to start
2. use a replica set (which does test for readiness)

Could the single-instance mode run the same readiness check that replicaset mode does?

**Comment by marcuspoehls** [comment]
@brettmc Hey Brett, thank you for pointing this out. Good catch 👍 Can you please prepare a pull request to improve the single instance "ready" handling to wait until MongoDB is actually ready to accept connections?
