### ISSUE TITLE
MongoDB path

### ISSUE THREAD

**Issue by jgcmarins** [supercharge/mongodb-github-action#5]
Hi, this action looks really promising.
I'd like to use with [mongodb-memory-server](https://github.com/nodkz/mongodb-memory-server) and point out where is MongoDB installation path to avoid `mongodb-memory-server` downloading MongoDB every time. Do you know where it's being installed on the container context? Thanks.

**Comment by jgcmarins** [comment]
Alright, I just used `which mongod` and it seems to work. Thanks.

**Comment by marcuspoehls** [comment]
@jgcmarins Hey João, thank you for sharing your solution. Good to know you already solved it.
