### ISSUE TITLE
tags and releases 

### ISSUE THREAD

**Issue by fpereira1** [supercharge/mongodb-github-action#53]
Hi.

It looks like with the 1.10.0 release a tag was created with the `v` prepended. Such as `v1.10.0`

In previous versions there was also a tag with v and without `1.9.0`.

Do you plan to use the new format from now on, or was it an oversight?

Thank you

**Comment by marcuspoehls** [comment]
@fpereira1 Oops, that's an oversight 😬 I'm going to create a 1.10.0 release without the prefix. I'm not planning to use the prefix

**Comment by marcuspoehls** [comment]
I’ve published a `1.10.0` release without the `v` prefix. I also left the `v1.10.0` release available in case you’re using it already
