### ISSUE TITLE
toomanyrequests: You have reached your pull rate limit.

### ISSUE THREAD

**Issue by vladkasianenko** [supercharge/mongodb-github-action#57]
![image](https://github.com/supercharge/mongodb-github-action/assets/14053728/693fe4fb-ba46-40cc-8acd-d7fa861e8b1a)

**Comment by marcuspoehls** [comment]
I remember that Docker allows you to increase your rate limit when using authenticated requests. You may need to log in to Docker. I don’t know how to do that in GitHub Actions, though
